stages:
  - test
  - deploy

default:
  image: ubuntu:latest
  cache:
    paths:
      - vendor/
  before_script:
    - chmod +x script/ci-setup
    - script/ci-setup
    - script/ci-bootstrap

test:
  stage: test
#  before_script:
  script:
    # this is needed to start using rvm
    - source /usr/local/rvm/scripts/rvm
    - script/ci-test
  only:
    - master
    - merge_requests

#deploy-gem:
#  stage: deploy
#  before_script:
#    - chmod +x ./deploy-gem
#  script: ./deploy-gem
#  only:
#    - master