stages:
  - test
  - deploy

default:
  image: ruby:latest
  cache:
    paths:
      - vendor/
  before_script:
    # upgrade bundler to latest version
    - gem install bundler
    # install required gems
    - bundle install --path vendor

test:
  stage: test
#  before_script:
  script:
    - script/ci-test.sh
  only:
    - master
    - merge_requests

#deploy-gem:
#  stage: deploy
#  before_script:
#    - chmod +x ./deploy-gem
#  script: ./deploy-gem
#  only:
#    - master