stages:
  - test
  - deploy

default:
  image: ubuntu:latest
  before_script:
    - ls
    - chmod +x ./script/ci-setup
    - chmod +x ./script/ci-setup
    - ./script/ci-setup
    - ./script/bootstrap

test:
  stage: test
  before_script:
    - chmod +x ./script/ci-build
  script: ./script/ci-build
  only:
    - master
    - merge_requests

deploy:
  stage: deploy
  before_script:
    - chmod +x ./script/deploy
  script: ./script/deploy
  only:
    - master