stages:
  - test
  - deploy

default:
  image: ubuntu:latest
  before_script:
    - chmod +x script/ci-setup
    - script/ci-setup

test:
  stage: test
#  before_script:
  script:
    - ls -lsa
    - git --version
    - source /usr/local/rvm/scripts/rvm
    - rvm
  only:
    - master
    - merge_requests

#deploy-gem:
#  stage: deploy
#  before_script:
#    - chmod +x ./deploy-gem
#  script: ./deploy-gem
#  only:
#    - master