stages:
  - test
  - deploy

default:
  image: ruby:latest
  cache:
    paths:
      - vendor/
  before_script:
    #- chmod +x script/ci-setup
    #- script/ci-setup
    # this is needed to start using rvm
    #- source /usr/local/rvm/scripts/rvm
    # install gems
    - bundle install --path vendor

test:
  stage: test
#  before_script:
  script:
    - script/ci-test
  only:
    - master
    - merge_requests

#deploy-gem:
#  stage: deploy
#  before_script:
#    - chmod +x ./deploy-gem
#  script: ./deploy-gem
#  only:
#    - master