stages:
  - test
  - deploy

default:
  image: ubuntu:latest
#  before_script:
#    - cd script
#    - chmod +x ci-setup
#    - chmod +x bootstrap
#    - ./ci-setup
#    - ./bootstrap

test:
  stage: test
#  before_script:
#    - chmod +x ./ci-build
  script:
    - ls -lsa
  only:
    - master
    - merge_requests

#deploy-gem:
#  stage: deploy
#  before_script:
#    - chmod +x ./deploy-gem
#  script: ./deploy-gem
#  only:
#    - master