stages:
  - test
  - deploy

default:
  image: ubuntu:latest
  before_script:
    - cd script
    - chmod +x ci-setup
    - chmod +x bootstrap
    - ./ci-setup
    - ./bootstrap

test:
  stage: test
  before_script:
    - chmod +x ./ci-build
  script: ./ci-build
  only:
    - master
    - merge_requests

deploy:
  stage: deploy
  before_script:
    - chmod +x ./deploy
  script: ./deploy
  only:
    - master