inherit_from: .rubocop_todo.yml

require: rubocop-jekyll

inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - vendor/**/*
    - doc/**/*

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
  IndentationWidth: 2

Layout/LineLength:
  Max: 85

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 25

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/MutableConstant:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/StringLiterals:
  EnforcedStyle: double_quotes
