inherit_from: .rubocop_todo.yml

require: rubocop-jekyll

inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - vendor/**/*

Layout/AlignHash:
  EnforcedHashRocketStyle: table

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
  IndentationWidth: 2

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 50

Metrics/LineLength:
  Max: 85

Metrics/MethodLength:
  Max: 25

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/StringLiterals:
  EnforcedStyle: double_quotes



