title: OpenMoji Jekyll Plugin
email: MahdiBaghbani@protonmail.com
description: Bring beautiful OpenMoji emojis to your Jekyll websites.
url: https://azadeh-afzar.gitlab.io
baseurl: Web-Development/OpenMoji-Jekyll-Plugin

minima:
  social_links:
    twitter: baghbani1
    github:  MahdiBaghbani
    gitlab: MahdiBaghbani

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-openmoji
